apiVersion: v1
kind: Service
metadata:
  name: etc-app
  namespace: etc
spec:
  type: NodePort
  selector:
    app: etc
    version: "1.0"
  ports:
  - port: 80
    targetPort: 8080

---
apiVersion: v1
kind: Service
metadata:
  name: community-app
  namespace: community
spec:
  type: NodePort
  selector:
    app: community
    version: "1.0"
  ports:
  - port: 80
    targetPort: 8080

---
apiVersion: v1
kind: Service
metadata:
  name: user-app
  namespace: user
spec:
  type: NodePort
  selector:
    app: user
    version: "1.0"
  ports:
  - port: 80
    targetPort: 8080

---
apiVersion: v1
kind: Service
metadata:
  name: board-app
  namespace: board
spec:
  type: NodePort
  selector:
    app: board
    version: "1.0"
  ports:
  - port: 80
    targetPort: 8080
