apiVersion: v1
kind: Service
metadata:
  name: community-app
  namespace: community
  labels:
    service: community
    project: tubeplus
    version: "1.0"
spec:
  type: ClusterIP
  selector:
    service: community
    project: tubeplus
    version: "1.0"
  ports:
  - port: 80
    targetPort: 8080

---

apiVersion: apps/v1
strategy:
  type: RollingUpdate
  rollingUpdate:
    maxUnavailable: 2
    maxSurge: 1
kind: Deployment
metadata:
  name: user
  namespace: tubeplus
  labels:
    service: user
    project: tubeplus
    version: "1.0"
spec:
  replicas: 1
  selector:
    matchLabels:
      service: user
      project: tubeplus
      version: "1.0"
  template:
    metadata:
      labels:
        service: user
        project: tubeplus
        version: "1.0"
    spec:
      containers:
      - name: user
        image: 7eom14/tubeplus-user:dev-1
        resources:
          limits:
            memory: "64Mi"
            cpu: "50m"
        ports:
        - containerPort: 8080
        env:
          - name: PORT
            valueFrom:
              configMapKeyRef:
                key: USER_HTTP_PORT
                name: port-config
