apiVersion: v1
kind: Service
metadata:
  name: etc-app
  namespace: tubeplus  
  labels:
    service: etc
    project: tubeplus
    version: "1.0"
spec:
  type: ClusterIP
  selector:
    service: etc
    project: tubeplus
    version: "1.0"
  ports:
  - port: 80
    targetPort: 8080

---

apiVersion: apps/v1
kind: Deployment
strategy: # rollback용
  type: RollingUpdate
  rollingUpdate:
    maxUnavailable: 2
    maxSurge: 1
metadata:
  name: etc
  namespace: tubeplus
  labels:
    service: etc
    project: tubeplus
    version: "1.0"
spec: # 볼륨
  replicas: 1 # replica 개수
  selector:
    matchLabels:
      service: etc
      project: tubeplus
      version: "1.0"
  template:
    metadata:
      labels:
        service: etc
        project: tubeplus
        version: "1.0"
    spec:
      containers:
      - name: etc
        image: 7eom14/tubeplus-etc:dev-1
        resources:
          limits:
            memory: "64Mi"
            cpu: "50m"
        ports:
        - containerPort: 8080
        env:
          - name: PORT
            valueFrom:
              configMapKeyRef:
                key: ETC_HTTP_PORT
                name: port-config
