apiVersion: v1
kind: Service
metadata:
  name: front-app
  namespace: tubeplus  
  labels:
    service: front
    project: tubeplus
    version: "1.0"
spec:
  type: LoadBalancer
  selector:
    service: front
    project: tubeplus
    version: "1.0"
  ports:
  - port: 80
    targetPort: 8080

---

apiVersion: apps/v1
kind: Deployment
strategy: # rollback용
  type: RollingUpdate
  rollingUpdate:
    maxUnavailable: 2
    maxSurge: 1
metadata:
  name: front
  namespace: tubeplus
  labels:
    service: front
    project: tubeplus
    version: "1.0"
spec:
  replicas: 1 
  selector:
    matchLabels:
      service: front
      project: tubeplus
      version: "1.0"
  template:
    metadata:
      labels:
        service: front
        project: tubeplus
        version: "1.0"
    spec:
      containers:
      - name: front
        image: 7eom14/tubeplus-front:dev-1
        resources:
          limits:
            memory: "64Mi"
            cpu: "50m"
        ports:
        - containerPort: 8080
        env:
          - name: PORT
            valueFrom:
              configMapKeyRef:
                key: FRONT_HTTP_PORT
                name: port-config
